version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      
    commands:
      - echo Installing Serverless
      - npm install -g serverless

  pre_build:
    commands:
      - echo Installing Source NPM Dependencies
      - npm install

  build:
    commands:
      - echo Deployment started on `date`
      - echo Depolying with Serverless Framework
      - serverless deploy -v -s $ENV_NAME

  post_build:
    commands:
      - echo Depolyment completed on `date`